### ISSUE TITLE
🐛 Bug Report:  My squad not properly visible in Mobile devices

### ISSUE THREAD

**Issue by bandya2003** [novuhq/hacksquad-website#106] opened 2022-10-25 19:23 UTC
### 📜 Description

The My Squad Page attributes aren't correctly visible or accessible on mobile devices.

Send a message to your squad button isn't visible.

Allow random people to join my team checkbox can't be ticked.

Even after rotating the device it is not visible.

### 👟 Reproduction steps

Make it responsive by adding margin borders and proper padding to mobile devices.

### 👍 Expected behavior

The checkbox and Send button should be visible on other devices too.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/61108642/197862928-81048713-7357-41cf-9396-91c60d9a602f.png)

![image](https://user-images.githubusercontent.com/61108642/197863084-92e5541c-d09b-49f7-813f-41784f168242.png)

![image](https://user-images.githubusercontent.com/61108642/197863116-40a355e2-a078-464d-89a2-f9f7eef19967.png)

### 💻 Operating system

Something else

### 🤖 Node Version

16.7.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by diwash007** [comment] 2022-10-26 01:37
Will be fixed by #89

**Comment by TheLearneer** [comment] 2022-10-26 02:32
Duplicate of #18

**Closed by TheLearneer** 2022-10-26 02:32 UTC
